### ISSUE TITLE
libc version mismatch

### ISSUE THREAD

**Issue by NuclearPowerNerd** [TomLebeda/chroma_code#1]
Hello,

I'd like to give `chroma_code` a try, but I seem to be missing some library files. I am running on ubuntu version 20.04.5. When I try to do `./chromacode -h` I get the following error.

```
./chromacode: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chromacode)
./chromacode: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chromacode)
./chromacode: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chromacode)
```

I ran `apt policy libc6` and got the following.

```
libc6:
  Installed: 2.31-0ubuntu9.9
  Candidate: 2.31-0ubuntu9.9
```
It seems I have an older version of `libc6`. Any idea how this could be resolved?

**Comment by TomLebeda** [comment]
Hello,
are you using the pre-compiled binaries or are you building from source?

**Comment by TomLebeda** [comment]
So I did a quick research since I'm not familiar with Ubuntu's packaging system, here is what I found: 
The version you are using (20.04.5) ships glibc v2.31 which is apparently too old. The obvious solution is to upgrade your system to some version that ships glibc version. If you can't or don't want to, there is probably some witchcraft that can force the package update without upgrading your system, but I don't know Ubuntu well enough to give any advice on that.

**Comment by NuclearPowerNerd** [comment]
I am using one of the pre-compiled binaries. Would building it myself make a difference?

I'd rather not mess with updating my personal system. I have other linux environments available to me though. I'll give this a shot on one of those as I do agree with you that the output (at least for Julia) appears to be superior to `minted`.

**Comment by TomLebeda** [comment]
I do think that compiling it on your system could help, the compiler will probably be forced to try it's best to use what is available, but I'm not 100% sure. If you try, please let me know.

If you have other systems available, you can try running it somewhere where the libc version is sufficient, it should help.

**Comment by NuclearPowerNerd** [comment]
So I built it locally and now it appears to at least run (I can do `chromacode -h`). However I am getting an error when I try the following.

`chromacode PATH/TO/MY/SOURCE/CODE/CODE.jl text.tex`

`error: unexpected argument 'PATH/TO/MY/SOURCE/CODE/CODE.jl' found`

I cloned [this](https://github.com/tree-sitter/tree-sitter-julia) repo to `/home/USERNAME/tree-sitter-julia/` and then added this location to the config file for tree-sitter so that it looks like this.

```
 "parser-directories": [
    "/home/USERNAME/github",
    "/home/USERNAME/src",
    "/home/USERNAME/source",
    "/home/USERNAME/tree-sitter-julia"
```

Any idea what might be going wrong?

**Comment by NuclearPowerNerd** [comment]
Okay so I was missing that I had to include the flags `-i` and `-o`. So now this works.

`chromacode -i PATH/TO/MY/SOURCE/CODE/CODE.jl -o text.tex`

I also moved the contents of `/home/USERNAME/tree-sitter-julia/` into `/home/USERNAME/source/` and now when I do `tree-sitter dump-languages` I get

```
scope: source.julia
parser: "/home/USERNAME/source/tree-sitter-julia/"
highlights: None
file_types: ["jl"]
content_regex: None
injection_regex: None
```
I'm guessing it is not set up correctly because everything is `None`? Was I supposed to do something besides just clone [this](https://github.com/tree-sitter/tree-sitter-julia) repo? When I try to run the file I get the following warning

```
WARNING: The command "tree-sitter highlight -H PATH/TO/MY/SOURCE/CODE/CODE.jl" finished, but returned error message: "No syntax highlighting config found for path "PATH/TO/MY/SOURCE/CODE/CODE.jl"
".
The output will probably be not correct.
This is probably not an issue of this program, but rather the external TreeSitter call.
```

**Comment by TomLebeda** [comment]
You are probably missing `queries/highlights.scm` file in the `tree-sitter-julia` directory. So TreeSitter doesn't know how to highlight. Most repositories already contain some basic highlighting queries, `tree-sitter-julia` is one of the exceptions that don't have it. 

You can just create the `queries` directory and put `highlights.scm` into it. For the content of the file, you can copy the example I provided [here](https://github.com/TomLebeda/chroma_code/blob/main/examples/highlights-julia.scm). 

Also pay attention to the config file (where you edit the paths): the highlighting queries correspond to the capture groups in the `theme`. If you copy my examples, it should match. But if you want to modify it, keep that in mind. 

I will close this issue because the libc version is solved. If you have some other problems, feel free to open new one.

**Comment by NuclearPowerNerd** [comment]
Yes - that fixed the issue for me. Now it works and looks fantastic. Thank you for creating this!
